import { StyleSheet } from 'react-native';

import { Palette } from '@/constants/Colors';
import { FloatingShadow, Radius, Spacing } from '@/constants/theme';

export const exploreStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F3EF',
  },
  mapArea: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Palette.surfaceMuted,
  },
  map: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  floatingChrome: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  markerWrap: {
    alignItems: 'center',
  },
  markerPin: {
    backgroundColor: '#D85A30',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    shadowColor: '#D85A30',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    borderWidth: 2,
    borderColor: 'white',
  },
  markerPinSelected: {
    backgroundColor: '#1A1A1A',
  },
  markerEmoji: {
    fontSize: 12,
  },
  markerPrice: {
    color: 'white',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  markerPointer: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#D85A30',
    alignSelf: 'center',
    marginTop: -1,
  },
  markerPointerSelected: {
    borderTopColor: '#1A1A1A',
  },
  markerBadge: {
    backgroundColor: '#FEF3C7',
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  markerBadgeText: {
    fontSize: 9,
    color: '#92400E',
    fontWeight: '700',
  },
  locationSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  locationSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#1A1A1A',
    paddingVertical: 0,
  },
  categoryChips: {
    marginTop: 0,
  },
  categoryChipsContent: {
    gap: 6,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  categoryChipActive: {
    backgroundColor: '#D85A30',
  },
  categoryChipLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#374151',
  },
  categoryChipLabelActive: {
    color: 'white',
  },
  nearMeButton: {
    position: 'absolute',
    bottom: 200,
    right: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    zIndex: 15,
  },
  recenterButton: {
    position: 'absolute',
    bottom: 148,
    right: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    zIndex: 15,
  },
  recenterIcon: {
    fontSize: 18,
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Palette.surface,
    borderTopLeftRadius: Radius.lg + 8,
    borderTopRightRadius: Radius.lg + 8,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderColor: Palette.borderSubtle,
    ...FloatingShadow,
  },
  sheetDragZone: {
    paddingBottom: Spacing.xs,
  },
  sheetBody: {
    flex: 1,
    minHeight: 0,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: Palette.border,
    marginBottom: Spacing.md,
  },
  sheetContent: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
    minHeight: 0,
  },
});
