import { Platform, StyleSheet } from 'react-native';

import { Palette } from '@/constants/Colors';
import { FloatingShadow, Spacing } from '@/constants/theme';

export const exploreStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Palette.background,
  },
  header: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: Palette.white,
    gap: 10,
    zIndex: 20,
  },
  mapArea: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#E8E4DC',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: Palette.background,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 48,
  },
  searchInput: {
    flex: 1,
    color: Palette.textPrimary,
    fontSize: 14,
    fontWeight: '400',
  },
  filterButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: Palette.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterPanelFloating: {
    position: 'absolute',
    top: 8,
    left: 16,
    right: 16,
    zIndex: 10,
    backgroundColor: Palette.white,
    borderRadius: 16,
    padding: 16,
    gap: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  filterSectionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  filterSectionSpacing: {
    marginTop: 4,
  },
  filterWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterPill: {
    height: 36,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: Palette.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    justifyContent: 'center',
  },
  filterPillActive: {
    backgroundColor: Palette.primary,
    borderColor: Palette.primary,
  },
  filterPillText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '500',
  },
  filterPillTextActive: {
    color: Palette.white,
  },
  applyFiltersBtn: {
    marginTop: 6,
    backgroundColor: Palette.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  applyFiltersText: {
    color: Palette.white,
    fontSize: 15,
    fontWeight: '600',
  },
  markerPin: {
    minWidth: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: Palette.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: Palette.white,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  markerPrice: {
    color: Palette.white,
    fontSize: 13,
    fontWeight: '800',
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Palette.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: -4 },
      },
      android: { elevation: 10 },
      default: {},
    }),
  },
  sheetDragZone: {
    paddingBottom: 4,
  },
  sheetBody: {
    flex: 1,
    minHeight: 0,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E5E7EB',
    marginBottom: 16,
  },
  sheetTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginBottom: 12,
  },
  sheetTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  bagCountBadge: {
    backgroundColor: Palette.primary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  bagCountText: {
    color: Palette.white,
    fontSize: 12,
    fontWeight: '600',
  },
  sheetContent: {
    flex: 1,
    paddingHorizontal: 16,
    minHeight: 0,
  },
  sheetEmpty: {
    paddingVertical: 32,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  sheetEmptyIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FAECE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetEmptyEmoji: {
    fontSize: 32,
  },
  sheetEmptyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
    marginTop: 16,
    textAlign: 'center',
  },
  sheetEmptySubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 22,
  },
  resetFiltersBtn: {
    marginTop: 20,
    backgroundColor: '#FAECE7',
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  resetFiltersText: {
    color: Palette.primaryDark,
    fontSize: 14,
    fontWeight: '600',
  },
  selectedCard: {
    backgroundColor: Palette.background,
    borderRadius: 16,
    padding: 14,
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 12,
    ...FloatingShadow,
  },
  selectedTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectedName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  categoryBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#FAECE7',
  },
  categoryBadgeText: {
    color: Palette.primaryDark,
    fontWeight: '600',
    fontSize: 12,
    textTransform: 'capitalize',
  },
  selectedMeta: {
    color: Palette.textSecondary,
    fontSize: 13,
    fontWeight: '500',
  },
  reserveButton: {
    alignSelf: 'flex-start',
    backgroundColor: Palette.primary,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  reserveButtonText: {
    color: Palette.white,
    fontSize: 14,
    fontWeight: '600',
  },
  listCard: {
    backgroundColor: Palette.background,
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  listPartner: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  listBagTitle: {
    fontSize: 13,
    color: Palette.textSecondary,
    fontWeight: '400',
    marginTop: 2,
  },
  listMeta: {
    fontSize: 12,
    color: Palette.textSecondary,
    marginTop: 4,
    fontWeight: '500',
  },
  listPrice: {
    color: Palette.primary,
    fontSize: 17,
    fontWeight: '700',
  },
});
