import { StyleSheet } from 'react-native';

import { Palette } from '@/constants/Colors';
import { FloatingShadow, Radius, Spacing } from '@/constants/theme';

export const exploreStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Palette.background,
  },
  mapArea: {
    flex: 1,
    position: 'relative',
    backgroundColor: Palette.surfaceMuted,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  floatingChrome: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  markerWrap: {
    alignItems: 'center',
  },
  markerPin: {
    backgroundColor: '#D85A30',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    shadowColor: '#D85A30',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    borderWidth: 2,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 52,
  },
  markerPrice: {
    color: 'white',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  markerPointer: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#D85A30',
    alignSelf: 'center',
    marginTop: -1,
  },
  recenterButton: {
    position: 'absolute',
    bottom: 180,
    right: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    zIndex: 15,
  },
  recenterIcon: {
    fontSize: 18,
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Palette.surface,
    borderTopLeftRadius: Radius.lg + 8,
    borderTopRightRadius: Radius.lg + 8,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderColor: Palette.borderSubtle,
    ...FloatingShadow,
  },
  sheetDragZone: {
    paddingBottom: Spacing.xs,
  },
  sheetBody: {
    flex: 1,
    minHeight: 0,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: Palette.border,
    marginBottom: Spacing.md,
  },
  sheetContent: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
    minHeight: 0,
  },
});
